#! /bin/bash -e

cd `dirname "$0"`
. common

case "$1" in
    prepare)
        devname=`basename "${device}"`
        while ! [ -d /sys/block/${devname} ] ; do
            devname=${devname:0:-1}
        done
        echo `basename "$0"` > /sys/block/${devname}/queue/scheduler
        ;;

    use)
        use
        ;;
esac
